<script src="{{ asset('support/vendor/global/global.min.js') }}"></script>
<script src="{{ asset('support/vendor/jquery-nice-select/js/jquery.nice-select.min.js') }}"></script>
<script src="{{ asset('support/vendor/apexchart/apexchart.js') }}"></script>
<script src="{{ asset('support/vendor/chart.js/Chart.bundle.min.js') }}"></script>
<script src="{{ asset('support/vendor/sweetalert2/dist/sweetalert2.min.js') }}"></script>
<script src="{{ asset('support/vendor/ckeditor/ckeditor.js') }}"></script>
<script src="{{ asset('support/vendor/peity/jquery.peity.min.js') }}"></script>
<script src="{{ asset('support/vendor/owl-carousel/owl.carousel.js') }}"></script>
<script src="{{ asset('support/js/custom.min.js') }}"></script>
<script src="{{ asset('support/js/dlabnav-init.js') }}"></script>
{{--  <script src="{{ asset('support/js/styleSwitcher.js') }}"></script>  --}}
